device: cuda:0
model: directecfp
embedding: directecfp
input_size: 200000
ecfp_length: 200000
ecfp_radius: 2 
D: 200000 
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True