device: "cuda:0"
model: rp
embedding: molformer 
ecfp_length:
ecfp_radius: 
input_size: 768
D: 1000000
# epochs: 10
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True