device: cuda:0
model: directecfp
embedding: directecfp
input_size: 1000000
ecfp_length: 1000000
ecfp_radius: 4
D: 1000000
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True