device: cuda:0
model: directecfp
embedding: directecfp
input_size: 500000
ecfp_length: 500000
ecfp_radius: 4 
D: 500000
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True