device: cuda:0
model: directecfp
embedding: directecfp
input_size: 10000
ecfp_length: 10000
ecfp_radius: 1 
D: 10000
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True