device: cuda:0
model: directecfp
embedding: directecfp
input_size: 100000
ecfp_length: 100000
ecfp_radius: 1
D: 100000
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True