device: cuda:0
model: directecfp
embedding: directecfp
input_size: 100
ecfp_length: 100
ecfp_radius: 2
D: 100
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True