device: cuda:0
model: directecfp
embedding: directecfp
input_size: 50000 
ecfp_length: 50000
ecfp_radius: 4 
D: 50000
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True