device: cuda:0
model: directecfp
embedding: directecfp
input_size: 1024
ecfp_length: 1024
ecfp_radius: 1
D: 1024
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True