device: "cuda:0"
model: rp
embedding: molformer-ecfp-combo 
ecfp_length: 1024
ecfp_radius: 1
input_size: 1792 
D: 1000000
# epochs: 10
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True