device: cuda:0
model: directecfp
embedding: directecfp
input_size: 16384 
ecfp_length: 16384
ecfp_radius: 1 
D: 16384
sim_metric: tanimoto
binarize_am: True
binarize_hv: True
bipolarize_am: False
bipolarize_hv: False