model: molehd
embedding: atomwise
input_size: 
ecfp_radius:
ngram_order:
D: 10000
# epochs: 10
device: cpu
sim_metric: cosine
binarize_am: False
binarize_hv: False
bipolarize_am: False
bipolarize_hv: True